Metrics/LineLength:
  Max: 130
Metrics/AbcSize:
  Max: 32
Metrics/MethodLength:
  Max: 25
Metrics/BlockLength:
  Max: 300
Metrics/ClassLength:
  Max: 300
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Max: 15
